enhancement : added new boilerplate
IEEE-VIT/templa-rs pull request #17
Opened 2021-10-03 05:18 UTC by mogiiee

i have added a new entry

2021-10-03 05:43 UTC, mogiiee commented
i have resolved the merge conflict

2021-10-03 06:18 UTC, mintbomb27 requested changes
Please check out the changes requested. Thank you for your contribution! :)

2021-10-03 06:18 UTC, mintbomb27 commented on submodules.json
> +
You might've removed a `{` while resolving the merge conflict. Please do keep that.

2021-10-03 06:18 UTC, mintbomb27 commented on submodules.json
> +    "tags" : ["none"]
If you have no tags, the repo won't be displayed in the results. You could add tags like `basic`,`repo` or stuff like that.

2021-10-03 06:42 UTC, mogiiee commented
@mintbomb27 please have a look at it now.

2021-10-03 09:18 UTC, mintbomb27 reviewed
Hey! Would be great if you could find some other repo that contains boilerplate for some framework's or language's code instead of a basic repo boilerplate. Can keep this PR open for your contribution. Marking accepted.

2021-10-04 06:53 UTC, mogiiee commented
@mintbomb27 could you please check it now... i have added a boilerplate for fastapi with mongodb in the correct order.

2021-10-04 08:20 UTC, closed without merging