feat: show progress bar when cloning a github repo
IEEE-VIT/templa-rs pull request #26
Opened 2021-10-05 05:01 UTC by mooyg

2021-10-05 05:03 UTC, mooyg commented
Used two libraries [progress bar lib](https://crates.io/crates/progress_bar) and [git2](https://crates.io/crates/git2).

2021-10-05 09:05 UTC, mintbomb27 requested changes
Please see the comments :)

2021-10-05 09:05 UTC, mintbomb27 commented on src/command.rs
> +    println!("PROJ NAME = {}", &proj_name);
Need not print the project again

2021-10-05 09:05 UTC, mintbomb27 commented on src/command.rs
> +    let mut progress_bar = ProgressBar::new(repo_size / 1000);
this might vary and even make the repo size 0. Why not set a 0 to 100% and map the repo size to that range?

2021-10-05 12:34 UTC, mooyg commented
Fixed

2021-10-06 04:08 UTC, mintbomb27 approved these changes
LGTM! Thanks for your contribution!

2021-10-06 04:44 UTC, merged